-- Run this file in Supabase SQL Editor before deploying the website.
create table if not exists public.skills (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 1 and 80),
  created_at timestamptz not null default now()
);

create table if not exists public.guestbook (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 1 and 80),
  content text not null check (char_length(content) between 1 and 500),
  created_at timestamptz not null default now()
);

alter table public.skills enable row level security;
alter table public.guestbook enable row level security;

drop policy if exists "Anyone can read skills" on public.skills;
create policy "Anyone can read skills"
  on public.skills for select
  to anon, authenticated
  using (true);

drop policy if exists "Anyone can leave a message" on public.guestbook;
create policy "Anyone can leave a message"
  on public.guestbook for insert
  to anon, authenticated
  with check (true);

insert into public.skills (name)
select name
from (values
  ('HTML & CSS'),
  ('JavaScript'),
  ('React / Node.js'),
  ('Supabase')
) as default_skills(name)
where not exists (select 1 from public.skills);